### ISSUE TITLE
Scary number of processes

### ISSUE THREAD

**Issue by MahmoudYounes** [seungukshin/cscope-code#18]
Building cscope.out invokes a massive number of processes. it also consumes a massive amount of memory causing other apps to be oom killed. I was wondering if there is a config/option that can be constraint/cap number of threads invoked.
 
![Screenshot from 2023-07-26 23-05-10](https://github.com/SeungukShin/cscope-code/assets/16405597/0e795f2d-2810-486b-ae2f-a51780bbc01f)

**Comment by lidaobing** [comment]
similar problem on my project, sounds the query will trigger `build`, but build has no guard to prevent several build start together.

**Comment by SeungukShin** [comment]
You can avoid this problem by disabling auto generation of a cscope database in setting. I'll make a executing queue to fix this issue next version.

**Comment by prateek-agrawal** [comment]
Faced same issue , this generally happens when the workspace is huge. 

1.  find . \( -path "./<dir to exclude>" -o -path "./tools" -o -path "./bootloader" -o -path "./output" -o -path "./buildroot" -o -path "./mk" -o -path "./kernel" -o -path "./dir_to_exclude3" \) -prune -o \( -name "*.h" -o -name "*.c" -o -name "*.hpp" -o -name "*.cpp" \) -print > cscope.files 

use above command to exclude unnecessary directories and files inside those directories for the cscope to track. 
2. Run csope -bRkq 
3. It would make cscope faster as now it is not tracking unnecessary files and directories.

**Comment by seungukshin** [comment]
Sorry for belated reply. I limited upto 2 processes for this. (https://github.com/seungukshin/cscope-code/commit/3f883165f05bb18b2c3e63e65d6e98f029aa77de)
